---
- name: Create and Assign VLAN
  hosts: 10.105.216.21
  connection: local
  gather_facts: false
  
  tasks:
  - name: CREATE VLAN
    ios_vlan: 
      vlan_id: "20"
      state: present 
      
  - name: Reset stupid ass connection because AWX does dumb shit with SSH
    meta: reset_connection
      
  - name: SET VLAN ON PORT
    ios_l2_interface:
      name: "GigabitEthernet1/0/2"
      access_vlan: "20"
      mode: access
